### ISSUE TITLE
Notifications still showing when disabled through command line

### ISSUE THREAD

**Issue by OrdinaryMagician** [christophgysin/pasystray#107] opened 2018-12-21 16:52 UTC
Pasystray shows notifications any time sound plays in Firefox even when I have them disabled. It gets really annoying that they just pop up on the corner of the screen all the time. I launch it with `-N none` but the setting seems to not affect those notifications.

**Comment by christophgysin** [comment] 2018-12-22 22:51
That certainly sounds like a bug. What notifications do you get? Can you attach the notification text or a screenshot?

**Comment by OrdinaryMagician** [comment] 2018-12-23 12:15
A Firefox icon with a volume bar (the volume varies depending on the site and sound played).
![2018-12-23-131216](https://user-images.githubusercontent.com/2286785/50383480-a003e300-06b4-11e9-9b2f-ab76a30feee3.png)

I'm guessing Firefox is opening and closing new streams for every sound it plays, which honestly sounds impractical.

**Comment by christophgysin** [comment] 2019-01-02 18:08
This is a duplicate of #103 and has already been fixed on master.

**Closed by christophgysin** 2019-01-02 18:08 UTC
