### ISSUE TITLE
systray icon stuck with light-colour theme

### ISSUE THREAD

**Issue by zecoj** [christophgysin/pasystray#154] opened 2021-12-10 03:40 UTC
I'm using v0.8.0-1 in Arch and the systray icon is stuck with the light colour theme, does not matter which icon theme is set. Reverting to v0.7.1-2 fixes the issue.

**Comment by christophgysin** [comment] 2021-12-10 18:44
Can you reproduce this with current master?

**Comment by dl2718** [comment] 2021-12-11 22:11
Similar issue v0.8.0-1 in Manjaro, downgrading to v0.7.1-2 fixes it. Regardless of which icon theme I use: Adwaita, Papurus etc. Pasystray overwrite white color to black.

**Comment by sbraz** [comment] 2021-12-12 00:51
Hi,
I can also see the problem with Awesome WM, the tray icon looks like this: ![image](https://user-images.githubusercontent.com/4833332/145696266-ac06682e-e45d-4566-bbf5-990f83634f95.png)

The latest commit (1f72c621cd40bb9d2bb691b9fa7b8f136bd2352d, which adds the `--symbolic-icons` option) does fix the problem (unless `--symbolic-icons` is used). Could you please create a new release from it?

By the way, I wouldn't mind trying the newer icons if they worked on a dark background :)

**Comment by christophgysin** [comment] 2021-12-12 06:47
Duplicate of #151

**Closed by christophgysin** 2021-12-12 06:47 UTC
