### ISSUE TITLE
Segmentation fault on PipeWire

### ISSUE THREAD

**Issue by wundrweapon** [christophgysin/pasystray#145] opened 2021-09-23 18:20 UTC
Whne Pulse is launched via `pipewire-pulse`, pasystray fails to launch with a segmentation fault. The only other information printed to the terminal are a Gtk-WARNING marked "Theme parsing error" and a Gtk-CRITICAL marked "assertion 'GTK_IS_WIDGET (widget)' failed".

Other Pulse applications, such as Discord, pavucontrol, and Steam games on Proton, work as expeted.

**Comment by christophgysin** [comment] 2021-09-24 19:58
I'm pretty sure this is a duplicate of #90.

**Closed by christophgysin** 2021-09-24 19:58 UTC
